version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/postgres?sslmode=disable
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["go", "run", "main.go"]

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
